tutor_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "instructors#index"
  resources :instructors
  resources :students
end

tutor_app/app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :students, dependent: :destroy
end

tutor_app/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :instructor
end

tutor_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

tutor_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

tutor_app/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end
end

tutor_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  #index page
  def index
    @students = Student.all
  end
 #show page
  def show
    @student = Student.find(params[:id])
  end
 #new
  def new
    @student = Student.new
    @instructor_instructor = Instructor.all.map{|instructor| instructor.name}
  end
 #edit
  def edit
    @student = Student.find(params[:id])
    # if @student.instructor == current_user
    #   @student.destroy
    # else
    #   flash[:alert] = "Only the original author can delete"
    # end
    # redirect_to students_path
  end
 #create
  def create
    @student = Student.new(student_params)
    # @student= current_user.students.create!(student_params)
    @student.instructor = Instructor.find_by(name: params[:student][:instructor])
    @student.save
    redirect_to student_path(@student)
  end
#update
  def update
   @student = Student.find(params[:id])
   @student.update(student_params)
   redirect_to student_path(@student)
 end
 #delete
 def destroy
   @student = Student.find(params[:id])
  # if @student.instructor == current_user
    @student.destroy
  # else
  #   flash[:alert] = "Only the original author can delete"
  # end
  redirect_to students_path
end

  private

  def student_params
    params.require(:student).permit(:name, :email_id)
  end
end

tutor_app/app/views/instructors/index.html.erb
<h1> Instructor list </h1>

<% @instructors.each do |instructor| %>
  <div class="instructor">
    <h2><a href="<%= instructor_path(instructor) %>"><%= instructor.name %></a></h2>
  </div>
<% end %>

tutor_app/app/views/instructors/show.html.erb
<h1><%= @instructor.name %></h1>
<%= link_to "Edit Instructor", edit_instructor_path(@instructor) %>
<%= link_to "Delete Instructor", instructor_path(@instructor), method: :delete %>

tutor_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "signIn">
    <% if !current_user %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% else %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <%= current_user.email %>
   <% end %>
 </div>
      <h1 class='logo'><%= link_to "Tutor App", root_path %></h1>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <nav>
      <h1>A Tutor The People Service!</h1>
      <h2><%= link_to "All instructors", instructors_path %> | <%= link_to "View All Students", students_path %> | <%= link_to "Create New Students", new_student_path %></h2>
    </nav>
    <%= yield %>

  </body>
</html>

tutor_app/app/views/students/edit.html.erb
<h2>Edit Student File</h2>

<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email_id %>
  <%= f.text_field :email_id %>

  <%= f.submit %>
<% end %>

<%= form_for @student, method: :delete do |f| %>
 <%= f.submit "Delete", class: "delete" %>
<% end %>

tutor_app/app/views/students/index.html.erb
<h1>Student list </h1>
  <% @students.each do |student| %>
  <div>
    <h2><%= link_to student.name, student_path(student) %> - <%= Instructor.find(student.instructor_id).name %></h2>

<% end %>
</div>

tutor_app/app/views/students/new.html.erb
<h1>Add new students here!</h1>
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email_id %>
  <%= f.text_field :email_id %>
  <%= f.select(:instructor, options_for_select(@instructor_instructor))%>

  <%= f.submit %>
<% end %>

tutor_app/app/views/students/show.html.erb
<h2><%= @student.name %></h2>
<h3><%= Instructor.find(@student.instructor_id).name %></h3>
<%= link_to "Edit Student", edit_student_path(@student) %>
<%= link_to "Delete Student", student_path(@student), method: :delete %>